In [1]:
import numpy as np
import pandas as pd


In [2]:
dataset = pd.read_csv("bikebuyer1.csv")

In [3]:
dataset.head()

ID Marital Status  Gender  Yearly Income  Children        Education  \
0  22711.0         Single    Male          30000       0.0  Partial College   
1  13555.0        Married  Female          40000       0.0  Graduate Degree   
2      NaN        Married    Male         160000       5.0  Partial College   
3      2.0         Single    Male         160000       0.0  Graduate Degree   
4  25410.0            NaN  Female          70000       2.0        Bachelors   

       Occupation Home Owner  Cars  Commute Distance         Region  Age  \
0        Clerical         No     1               1.0         Europe   33   
1        Clerical        Yes     0               1.0         Europe   37   
2    Professional         No     3               2.0         Europe   55   
3      Management        Yes     2               5.0        Pacific   47   
4  Skilled Manual         No     1               1.0  North America   38   

  Bike Buyer  
0        Yes  
1        Yes  
2         No  
3         No  
4        Yes

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6997 entries, 0 to 6996
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   ID                6996 non-null   float64
 1   Marital Status    6981 non-null   object 
 2   Gender            6968 non-null   object 
 3   Yearly Income     6997 non-null   int64  
 4   Children          6979 non-null   float64
 5   Education         6997 non-null   object 
 6   Occupation        6997 non-null   object 
 7   Home Owner        6997 non-null   object 
 8   Cars              6997 non-null   int64  
 9   Commute Distance  6968 non-null   float64
 10  Region            6997 non-null   object 
 11  Age               6997 non-null   int64  
 12  Bike Buyer        6997 non-null   object 
dtypes: float64(3), int64(3), object(7)
memory usage: 710.8+ KB


In [5]:
dataset.describe()

ID  Yearly Income     Children         Cars  \
count   6996.000000    6997.000000  6979.000000  6997.000000   
mean   17744.435249   57020.151493     1.111621     1.586823   
std     4337.428859   32080.449720     1.600912     1.146782   
min        2.000000       0.000000     0.000000     0.000000   
25%    14249.750000   30000.000000     0.000000     1.000000   
50%    17406.500000   60000.000000     0.000000     2.000000   
75%    20609.500000   70000.000000     2.000000     2.000000   
max    29476.000000  170000.000000     5.000000     4.000000   

       Commute Distance          Age  
count       6968.000000  6997.000000  
mean           4.210103    45.107332  
std            2.926211    11.916654  
min            1.000000    25.000000  
25%            1.000000    36.000000  
50%            4.000000    44.000000  
75%            6.000000    53.000000  
max           13.000000    96.000000

In [6]:
#check for missing values
dataset.isnull().any()

ID                   True
Marital Status       True
Gender               True
Yearly Income       False
Children             True
Education           False
Occupation          False
Home Owner          False
Cars                False
Commute Distance     True
Region              False
Age                 False
Bike Buyer          False
dtype: bool

In [7]:
#marital status we fill missing values using mode as it is textual data
dataset['Marital Status'].fillna(dataset['Marital Status'].mode()[0],inplace=True)
dataset['Gender'].fillna(dataset['Gender'].mode()[0],inplace=True)
dataset['Children'].fillna(dataset['Children'].median(),inplace=True)
dataset['Commute Distance'].fillna(dataset['Commute Distance'].mean(),inplace=True)

In [8]:
#To understand why we have taken mode()[0] in above cell
dataset['Marital Status'].mode()

#Answer of mode operations is 'Married' which is in '0th' index, thats the reason we choosed mode()[0] so that 
#all missed rows in the column will be replaced with Married

#Samw holds for Gender as well

0    Married
dtype: object

In [9]:
#remove the columns which are not really making great impact on output varaible 'Bike Buyer'
dataset.drop(['ID','Education','Home Owner'],axis=1,inplace=True)

In [10]:
dataset

Marital Status  Gender  Yearly Income  Children      Occupation  Cars  \
0            Single    Male          30000       0.0        Clerical     1   
1           Married  Female          40000       0.0        Clerical     0   
2           Married    Male         160000       5.0    Professional     3   
3            Single    Male         160000       0.0      Management     2   
4           Married  Female          70000       2.0  Skilled Manual     1   
...             ...     ...            ...       ...             ...   ...   
6992        Married    Male         100000       4.0    Professional     3   
6993        Married  Female         130000       4.0    Professional     4   
6994        Married  Female         160000       5.0      Management     2   
6995         Single  Female         120000       5.0    Professional     3   
6996        Married    Male         130000       5.0    Professional     3   

      Commute Distance         Region  Age Bike Buyer  
0                  1.0         Europe   33        Yes  
1                  1.0         Europe   37        Yes  
2                  2.0         Europe   55         No  
3                  5.0        Pacific   47         No  
4                  1.0  North America   38        Yes  
...                ...            ...  ...        ...  
6992               1.0         Europe   52         No  
6993               2.0         Europe   52         No  
6994               1.0         Europe   53         No  
6995               1.0         Europe   54         No  
6996               2.0         Europe   54         No  

[6997 rows x 10 columns]

In [11]:
dataset['Marital Status'].unique()

array(['Single', 'Married'], dtype=object)

In [12]:
dataset['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [13]:
dataset['Occupation'].unique()

array(['Clerical', 'Professional', 'Management', 'Skilled Manual',
       'Manual'], dtype=object)

In [14]:
dataset['Region'].unique()

array(['Europe', 'Pacific', 'North America'], dtype=object)

In [17]:
#Now let us perform label encoding ie converting textual data into numerical data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['Marital Status'] = le.fit_transform(dataset['Marital Status'])
dataset['Gender'] = le.fit_transform(dataset['Gender'])
dataset['Occupation'] = le.fit_transform(dataset['Occupation'])
dataset['Region'] = le.fit_transform(dataset['Region'])
dataset['Bike Buyer'] = le.fit_transform(dataset['Bike Buyer'])






In [19]:
#Check whether Label Encoding is working or not
dataset

#In answer you should see all data converted into numerical. So understanding is LabelEncoding is performed

Marital Status  Gender  Yearly Income  Children  Occupation  Cars  \
0                  1       1          30000       0.0           0     1   
1                  0       0          40000       0.0           0     0   
2                  0       1         160000       5.0           3     3   
3                  1       1         160000       0.0           1     2   
4                  0       0          70000       2.0           4     1   
...              ...     ...            ...       ...         ...   ...   
6992               0       1         100000       4.0           3     3   
6993               0       0         130000       4.0           3     4   
6994               0       0         160000       5.0           1     2   
6995               1       0         120000       5.0           3     3   
6996               0       1         130000       5.0           3     3   

      Commute Distance  Region  Age  Bike Buyer  
0                  1.0       0   33           1  
1                  1.0       0   37           1  
2                  2.0       0   55           0  
3                  5.0       2   47           0  
4                  1.0       1   38           1  
...                ...     ...  ...         ...  
6992               1.0       0   52           0  
6993               2.0       0   52           0  
6994               1.0       0   53           0  
6995               1.0       0   54           0  
6996               2.0       0   54           0  

[6997 rows x 10 columns]

In [20]:
#for Marital Status - Married = 0, Single = 1 (no need of 1 hot encoding as already data is in binary format)

#for Gender - Female = 0, Male = 1 (no need of 1 hot encoding as already data is in binary format)

#Occupation - 0,1,2,3,4 (1 hot encoding is required)

#Region - 0,1,2 (1 hot encoding is required)




In [22]:
#separate the output variable from the whole dataset
x = dataset.iloc[:,0:9].values
y = dataset.iloc[:,9:10].values

In [23]:
#total input variables ie x

array([[1.0e+00, 1.0e+00, 3.0e+04, ..., 1.0e+00, 0.0e+00, 3.3e+01],
       [0.0e+00, 0.0e+00, 4.0e+04, ..., 1.0e+00, 0.0e+00, 3.7e+01],
       [0.0e+00, 1.0e+00, 1.6e+05, ..., 2.0e+00, 0.0e+00, 5.5e+01],
       ...,
       [0.0e+00, 0.0e+00, 1.6e+05, ..., 1.0e+00, 0.0e+00, 5.3e+01],
       [1.0e+00, 0.0e+00, 1.2e+05, ..., 1.0e+00, 0.0e+00, 5.4e+01],
       [0.0e+00, 1.0e+00, 1.3e+05, ..., 2.0e+00, 0.0e+00, 5.4e+01]])

In [26]:
#output variable ie y
y

array([[1],
       [1],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [27]:
#x has got total 9 columns
x.shape

(6997, 9)

In [28]:
#y has got only 1 column ie output variable
y.shape

(6997, 1)

In [30]:
#now lets perform 1 hot encoding to Occupation (0,1,2,3,4) and Region (0,1,2) columns so that we should get
# 9 - 2 + (5+3) = 15
#total_columns(9) - Occupation&Region(2) + (8 new columns) = 15 overall columns

#in next cell we shall perform all these operations


In [37]:
#one hot encoding
from sklearn.preprocessing import OneHotEncoder
oh = OneHotEncoder()
z = oh.fit_transform(x[:,4:5]).toarray() # Occupation column - converting into 5 columns
w = oh.fit_transform(x[:,7:8]).toarray() # Region column - converting into 3 columns




In [38]:
z

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.]])

In [39]:
w

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [40]:
x.shape

(6997, 9)

In [41]:
#deleting Occupation and Region columns
x = np.delete(x,[4,7],axis=1)

In [43]:
x.shape
#after deleting these 2 columns it became (9-2) = 7

(6997, 7)

In [44]:
#now adding one hot encoded columns to x
x=np.concatenate((x,z,w),axis=1)

In [46]:
x.shape
# after adding one hot encoded columns (5+3) to above (7) it will be total (15)

(6997, 15)

In [47]:
#Now split the dataset into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [48]:
#question paper
x_test.shape

(1400, 15)

In [49]:
#prepared quesitons
x_train.shape

(5597, 15)

In [51]:
#Standard Scaling - To normalize values 
#for example salary column has got values from 3lakh to 1crore so range is huge thats why we need to perform SS
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [52]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(x_train,y_train)


/Users/ychinmka@in.ibm.com/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [53]:
y_pred = logreg.predict(x_test)

In [54]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [55]:
y

array([[1],
       [1],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [56]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_pred,y_test)

In [58]:
#let us check how accurate our model is predicting
acc
#model predicting 86% correctly

0.8607142857142858

In [ ]:
#Our all we performed below steps
#imported libraries
#read dataset
#tested for missing values
#filled missing values 
#did label encoding
#did one hot encoding
#split the data and train and test
#trained the the model
#tested the model
#checked the accuracy of the model
